#!/usr/bin/env ruby


case RbConfig::CONFIG['host_os']
when /darwin|linux/i
  require_relative 'platforms/nix'
  NixCLI.start(ARGV)
when /mswin|mingw|cygwin/i
  raise "Windows is not supported yet"
end
